package me.saro.kit.enums

enum class Transformation(val value: String) {
    AES_ECB_NoPadding("AES/ECB/NoPadding"),
    AES_ECB_PKCS5Padding("AES/ECB/PKCS5Padding"),
    AES_CBC_NoPadding("AES/CBC/NoPadding"),
    AES_CBC_PKCS5Padding("AES/CBC/PKCS5Padding"),
    AES_CFB_NoPadding("AES/CFB/NoPadding"),
    AES_CFB_PKCS5Padding("AES/CFB/PKCS5Padding"),
    AES_OFB_NoPadding("AES/OFB/NoPadding"),
    AES_OFB_PKCS5Padding("AES/OFB/PKCS5Padding"),
    DES_ECB_NoPadding("DES/ECB/NoPadding"),
    DES_ECB_PKCS5Padding("DES/ECB/PKCS5Padding"),
    DES_CBC_NoPadding("DES/CBC/NoPadding"),
    DES_CBC_PKCS5Padding("DES/CBC/PKCS5Padding"),
    DES_CFB_NoPadding("DES/CFB/NoPadding"),
    DES_CFB_PKCS5Padding("DES/CFB/PKCS5Padding"),
    DES_OFB_NoPadding("DES/OFB/NoPadding"),
    DES_OFB_PKCS5Padding("DES/OFB/PKCS5Padding"),
    DESede_ECB_NoPadding("DESede/ECB/NoPadding"),
    DESede_ECB_PKCS5Padding("DESede/ECB/PKCS5Padding"),
    DESede_CBC_NoPadding("DESede/CBC/NoPadding"),
    DESede_CBC_PKCS5Padding("DESede/CBC/PKCS5Padding"),
    DESede_CFB_NoPadding("DESede/CFB/NoPadding"),
    DESede_CFB_PKCS5Padding("DESede/CFB/PKCS5Padding"),
    DESede_OFB_NoPadding("DESede/OFB/NoPadding"),
    DESede_OFB_PKCS5Padding("DESede/OFB/PKCS5Padding"),
    RSA_ECB_PKCS1Padding("RSA/ECB/PKCS1Padding"),
    RSA_ECB_OAEPWithSHA1AndMGF1Padding("RSA/ECB/OAEPWithSHA-1AndMGF1Padding"),
    RSA_ECB_OAEPWithSHA256AndMGF1Padding("RSA/ECB/OAEPWithSHA-256AndMGF1Padding")
}